-- 角色体系：用户角色（USER/MERCHANT/ADMIN），商品挂商家（seller）
CREATE TABLE IF NOT EXISTS `user_role` (`USER` VARCHAR(191) NOT NULL, `MERCHANT` VARCHAR(191) NOT NULL, `ADMIN` VARCHAR(191) NOT NULL) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
INSERT INTO `user_role` (`USER`, `MERCHANT`, `ADMIN`) VALUES ('USER', 'USER', 'USER'), ('MERCHANT', 'MERCHANT', 'MERCHANT'), ('ADMIN', 'ADMIN', 'ADMIN');
ALTER TABLE `users` ADD COLUMN `role` ENUM('USER', 'MERCHANT', 'ADMIN') NOT NULL DEFAULT 'USER';
ALTER TABLE `products` ADD COLUMN `seller_id` INT NULL;
CREATE INDEX `products_seller_id_idx` ON `products`(`seller_id`);
ALTER TABLE `products` ADD CONSTRAINT `products_seller_id_fkey` FOREIGN KEY (`seller_id`) REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
